export const pages = {
  es: {
    home: {
      eyebrow: 'Ingeniería e integración tecnológica desde Colombia',
      title: 'Tecnología avanzada para proteger, conectar y anticipar.',
      lead: 'Eagle Commercial integra soluciones de ingeniería y alta tecnología para defensa, seguridad, infraestructura crítica y organizaciones que operan en entornos donde la confiabilidad no es negociable.',
      primary: 'Conozca nuestras capacidades',
      secondary: 'Hable con un especialista',
      heroNotes: ['Tecnología seleccionada según la misión', 'Integración, despliegue y soporte local', 'Información técnica bajo acceso controlado'],
      principle: 'Soluciones diseñadas alrededor de la misión, no alrededor de un catálogo.',
      principleItems: ['Ingeniería', 'Integración', 'Despliegue', 'Soporte'],
      introEyebrow: 'Compañía',
      introTitle: 'Integramos tecnología para operaciones críticas.',
      introText: 'Eagle Commercial es una empresa colombiana especializada en identificar, integrar e implementar soluciones tecnológicas para organizaciones públicas y privadas. Combinamos ingeniería, conocimiento del entorno local, acceso a proveedores especializados y acompañamiento técnico para convertir necesidades complejas en capacidades confiables.',
      introText2: 'Nuestro trabajo comprende la evaluación inicial, el diseño de la arquitectura, la gestión logística, la instalación, la capacitación y el soporte durante el ciclo de vida.',
      showcaseEyebrow: 'Soluciones destacadas',
      showcaseTitle: 'Capacidades que generan impacto desde el primer vistazo.',
      showcaseLead: 'Integramos soluciones tecnológicas de alto valor para operación remota, vigilancia técnica, monitoreo RF, continuidad operacional y protección de infraestructuras críticas.',
      partnerEyebrow: 'Relaciones tecnológicas',
      partnerTitle: 'Marcas y tecnologías de referencia para proyectos especializados.',
      partnerLead: 'La página pública puede mostrar alianzas y líneas de solución de forma institucional, mientras el detalle técnico y comercial se comparte bajo validación del requerimiento.',
      clientsEyebrow: 'Experiencia institucional',
      clientsTitle: 'Referencias visibles en un panel dinámico.',
      clientsLead: 'En lugar de un bloque estático, proponemos un panel continuo en movimiento con entidades con las que Eagle Commercial ha trabajado, manteniendo presencia visual sin sobrecargar la página.',
      clientsNote: 'Antes de publicar logotipos institucionales o de terceros, recomendamos validar autorización de uso y lineamientos de marca.',
      capabilityEyebrow: 'Capacidades',
      capabilityTitle: 'Tecnología articulada como un sistema.',
      capabilityLead: 'Presentamos capacidades generales, no catálogos públicos. La configuración, disponibilidad y alcance se definen después de comprender el requerimiento y validar el marco aplicable.',
      sectorsEyebrow: 'Sectores',
      sectorsTitle: 'Tecnología que trasciende un solo entorno.',
      sectorsLead: 'Nuestras capacidades pueden adaptarse a organizaciones públicas y privadas que necesitan proteger activos, mantener comunicaciones, supervisar operaciones o actuar en escenarios complejos.',
      processEyebrow: 'Metodología',
      processTitle: 'De la necesidad a la capacidad operacional.',
      processLead: 'No nos limitamos a suministrar equipos. Diseñamos una solución coherente, acompañamos su implementación y ayudamos a preservar su utilidad en el tiempo.',
      diffEyebrow: 'Diferenciadores',
      diffTitle: 'Una capacidad integral, respaldada localmente.',
      confidentialityEyebrow: 'Confidencialidad',
      confidentialityTitle: 'La tecnología estratégica requiere discreción.',
      confidentialityText: 'Parte del portafolio y de los proyectos está sujeta a restricciones de confidencialidad. La información técnica detallada se comparte únicamente con organizaciones y usuarios autorizados, después de validar el alcance del requerimiento.',
      groupEyebrow: 'Eagle Group',
      groupTitle: 'Una estructura preparada para proyectos completos.',
      groupText: 'El ecosistema Eagle articula capacidades comerciales, técnicas, logísticas, de almacenamiento y gestión aduanera para acompañar proyectos desde su planeación hasta la entrega y el soporte.',
      finalTitle: 'Conversemos sobre su próxima capacidad.',
      finalText: 'Cuéntenos el entorno, el desafío o el resultado que necesita alcanzar. Nuestro equipo orientará el siguiente paso sin solicitar información sensible por canales públicos.'
    },
    company: {
      eyebrow: 'Nuestra compañía',
      title: 'Ingeniería, tecnología y confianza para entornos exigentes.',
      lead: 'Eagle Commercial S.A. articula capacidades de ingeniería, integración, implementación y soporte para organizaciones públicas y privadas en Colombia.',
      thesisTitle: 'Más que suministrar tecnología, construimos capacidades.',
      thesisText: 'Cada proyecto comienza con una necesidad operacional, no con un producto. Analizamos el entorno, las restricciones, la infraestructura disponible y el resultado esperado antes de seleccionar e integrar tecnologías.',
      thesisText2: 'Nuestra función es conectar proveedores especializados con el contexto local y acompañar el proyecto desde la definición hasta el soporte durante su ciclo de vida.',
      principlesTitle: 'Principios que orientan nuestro trabajo',
      principles: [
        { title: 'Responsabilidad', text: 'La tecnología se propone, integra y entrega dentro del marco legal, contractual y ético aplicable.' },
        { title: 'Confidencialidad', text: 'La información técnica, comercial y operacional se comparte según necesidad, autorización y nivel de acceso.' },
        { title: 'Rigurosidad', text: 'Las decisiones se sustentan en requerimientos, compatibilidad, pruebas, documentación y trazabilidad.' },
        { title: 'Continuidad', text: 'Consideramos capacitación, mantenimiento, garantías y evolución desde el diseño inicial.' }
      ],
      modelEyebrow: 'Modelo de trabajo',
      modelTitle: 'Un punto de articulación entre tecnología internacional y necesidades locales.',
      modelText: 'Eagle Commercial combina conocimiento del mercado colombiano, gestión de proyectos, relacionamiento con fabricantes y proveedores, logística especializada, implementación y soporte técnico.',
      audienceTitle: 'Trabajamos con organizaciones que no pueden improvisar.',
      audienceText: 'Entidades públicas, infraestructura crítica, compañías privadas, operadores industriales y aliados internacionales encuentran en Eagle un interlocutor para estructurar proyectos tecnológicos complejos.',
      finalTitle: 'Conozca cómo abordamos un proyecto.',
      finalText: 'Nuestra metodología permite avanzar de forma ordenada desde el requerimiento hasta el despliegue y el soporte.'
    },
    capabilities: {
      eyebrow: 'Capacidades',
      title: 'Una visión de portafolio sin exponer información sensible.',
      lead: 'La información pública describe beneficios y escenarios generales. Los modelos, marcas, especificaciones, configuraciones y alcances técnicos se comparten únicamente durante un proceso autorizado.',
      noteTitle: 'Información técnica bajo contexto y autorización',
      noteText: 'La disponibilidad, configuración y alcance de cada solución dependen del análisis técnico, el marco regulatorio, las condiciones del proyecto y la autorización para compartir información.',
      processTitle: 'Cómo se consulta una capacidad',
      process: ['Comparta el objetivo general sin datos reservados.', 'Nuestro equipo valida el contexto y el nivel de acceso.', 'Se define un canal apropiado y, cuando corresponda, un acuerdo de confidencialidad.', 'Se presenta una arquitectura ajustada al requerimiento.'],
      finalTitle: '¿Tiene una necesidad que no aparece aquí?',
      finalText: 'Las capacidades pueden combinarse en proyectos a la medida. Describa el resultado esperado y el entorno general.'
    },
    sectors: {
      eyebrow: 'Sectores',
      title: 'Tecnología para operaciones públicas y privadas.',
      lead: 'El valor de una capacidad depende del contexto. Adaptamos arquitectura, despliegue, capacitación y soporte a la realidad de cada sector.',
      crossTitle: 'Un mismo principio, diferentes misiones.',
      crossText: 'Proteger una instalación, inspeccionar un activo, mantener conectividad o coordinar una emergencia exige comprender riesgos, usuarios, infraestructura y regulación. Por eso evitamos soluciones genéricas.',
      finalTitle: 'Explore una arquitectura para su sector.',
      finalText: 'Converse con nuestro equipo sobre el entorno, los activos y el resultado que necesita alcanzar.'
    },
    engineering: {
      eyebrow: 'Ingeniería e integración',
      title: 'Diseñamos alrededor del resultado operacional.',
      lead: 'La selección de tecnología es una etapa del proceso. Antes definimos el problema, las interfaces, los riesgos, los criterios de aceptación y el plan de sostenimiento.',
      architectureTitle: 'Una arquitectura completa considera más que el equipo.',
      architectureItems: [
        { title: 'Personas', text: 'Roles, perfiles, capacitación, carga operativa y transferencia de conocimiento.' },
        { title: 'Procesos', text: 'Flujos de trabajo, escalamiento, documentación, gobierno y criterios de decisión.' },
        { title: 'Tecnología', text: 'Compatibilidad, integración, comunicaciones, procesamiento, energía y ciberseguridad.' },
        { title: 'Entorno', text: 'Infraestructura, clima, movilidad, regulación, logística y restricciones de operación.' }
      ],
      evidenceTitle: 'Entregables que facilitan la trazabilidad',
      evidenceItems: ['Definición de alcance y supuestos', 'Arquitectura funcional', 'Plan de integración y pruebas', 'Criterios de aceptación', 'Plan de capacitación', 'Documentación de entrega', 'Plan de soporte y continuidad'],
      finalTitle: 'Estructuremos el proyecto antes de hablar de referencias.',
      finalText: 'Una conversación inicial bien planteada reduce riesgos, evita compras aisladas y acelera la definición de una solución viable.'
    },
    support: {
      eyebrow: 'Soporte y ciclo de vida',
      title: 'La entrega es el inicio de la operación.',
      lead: 'Una capacidad tecnológica conserva su valor cuando existe acompañamiento, conocimiento, mantenimiento, documentación y una ruta de evolución.',
      modelTitle: 'Soporte ajustado al nivel de criticidad.',
      modelText: 'El alcance se define contractualmente según ubicación, disponibilidad requerida, tiempos de respuesta, repuestos, garantías, acceso a proveedores y restricciones de seguridad.',
      continuityTitle: 'Continuidad desde el diseño',
      continuityItems: ['Identificación de componentes críticos', 'Matriz de soporte y escalamiento', 'Plan de mantenimiento', 'Gestión de obsolescencia', 'Respaldo documental', 'Capacitación recurrente'],
      finalTitle: '¿Necesita soporte para una capacidad existente?',
      finalText: 'Comparta únicamente la categoría general y el tipo de novedad. Nuestro equipo indicará el canal seguro para continuar.'
    },
    group: {
      eyebrow: 'Eagle Group',
      title: 'Ingeniería, logística y comercio exterior coordinados.',
      lead: 'Los proyectos especializados requieren más que selección tecnológica. También exigen almacenamiento, preparación, trazabilidad, nacionalización y coordinación documental.',
      flowTitle: 'Una cadena articulada para reducir fricción.',
      flowSteps: ['Estructuración técnica y comercial', 'Coordinación con proveedores', 'Gestión logística y almacenamiento', 'Procesos aduaneros aplicables', 'Entrega, implementación y soporte'],
      governanceTitle: 'Cada servicio mantiene su alcance y responsabilidad.',
      governanceText: 'Las denominaciones legales, habilitaciones y condiciones de servicio deben validarse antes de publicación. La contratación y ejecución se realizan según la entidad y el alcance correspondiente.',
      finalTitle: 'Converse con el punto de entrada adecuado.',
      finalText: 'Eagle Commercial orientará el requerimiento hacia el componente técnico, logístico o aduanero pertinente.'
    },
    contact: {
      eyebrow: 'Contacto',
      title: 'Conversemos sin exponer información sensible.',
      lead: 'Describa el objetivo general, el sector y el resultado esperado. Nuestro equipo definirá un canal apropiado cuando el requerimiento exija confidencialidad.',
      detailsTitle: 'Información de contacto',
      formTitle: 'Solicitar orientación',
      formIntro: 'Los campos marcados son obligatorios. No adjunte documentos ni incluya especificaciones, ubicaciones sensibles o datos clasificados.',
      types: ['Información corporativa', 'Evaluación de una necesidad', 'Proyecto tecnológico', 'Soporte técnico', 'Alianza internacional', 'Solicitud de acceso', 'Otro'],
      urgency: ['Planeación', 'Durante este trimestre', 'En las próximas semanas', 'Incidente o continuidad operacional'],
      submit: 'Preparar mensaje',
      privacyText: 'Autorizo el tratamiento de mis datos para atender esta solicitud, de acuerdo con la política aplicable.'
    },
    access: {
      eyebrow: 'Área autorizada',
      title: 'Información técnica para usuarios previamente validados.',
      lead: 'La información reservada debe alojarse en una plataforma separada con autenticación, control de roles, registro de actividad y acuerdos de confidencialidad.',
      loginTitle: 'Iniciar sesión',
      requestTitle: 'Solicitar acceso',
      loginButton: 'Ingresar',
      requestButton: 'Enviar solicitud',
      rulesTitle: 'Criterios mínimos del sistema definitivo',
      rules: ['Autenticación multifactor', 'Aprobación manual de usuarios', 'Acceso por entidad, rol y proyecto', 'Registro de actividad y descargas', 'Caducidad de enlaces y permisos', 'Aceptación de términos y NDA', 'Alojamiento y cifrado aprobados por TI']
    },
    privacy: {
      eyebrow: 'Privacidad y cookies',
      title: 'Transparencia sobre el uso de información.',
      lead: 'Este texto es un borrador funcional para el prototipo y requiere revisión jurídica antes de publicarse.',
      sections: [
        { title: 'Alcance', text: 'La política debe explicar qué información recopila el sitio, con qué finalidad, durante cuánto tiempo se conserva y con quién puede compartirse.' },
        { title: 'Formularios', text: 'Los datos suministrados se utilizarían para responder solicitudes, evaluar oportunidades, coordinar soporte y gestionar relaciones comerciales autorizadas.' },
        { title: 'Cookies', text: 'El prototipo no incorpora analítica ni publicidad. Solo utiliza almacenamiento local para recordar la preferencia del aviso de cookies.' },
        { title: 'Seguridad', text: 'La versión productiva debe aplicar controles técnicos y administrativos proporcionales al riesgo, incluyendo cifrado, control de acceso y trazabilidad.' },
        { title: 'Derechos', text: 'La política definitiva debe describir los canales para consultar, actualizar, rectificar, suprimir información o revocar autorizaciones cuando proceda.' },
        { title: 'Actualizaciones', text: 'Toda modificación debe indicar fecha de vigencia, responsable y mecanismo de notificación.' }
      ]
    },
    data: {
      eyebrow: 'Tratamiento de datos personales',
      title: 'Aviso de privacidad y autorización.',
      lead: 'Contenido basado en la política pública existente. Debe ser revisado y actualizado por el área jurídica antes de migrarlo al nuevo sitio.',
      intro: 'Eagle Commercial S.A., identificada con NIT 830.040.391-7 y domiciliada en Bogotá, actúa como responsable del tratamiento de la información personal suministrada en el marco de solicitudes, relaciones comerciales, eventos, procesos de contratación y demás interacciones autorizadas.',
      purposesTitle: 'Finalidades generales',
      purposes: ['Atender solicitudes y mantener bases de datos internas.', 'Gestionar invitaciones, eventos, cursos, seminarios y capacitaciones.', 'Evaluar satisfacción y realizar estudios o diagnósticos.', 'Desarrollar actividades comerciales y de relacionamiento autorizadas.', 'Gestionar proveedores y procesos de contratación.', 'Generar estadísticas e informes.', 'Responder peticiones y obligaciones legales.', 'Transmitir información a aliados o filiales cuando exista base jurídica y autorización aplicable.'],
      rightsTitle: 'Derechos del titular',
      rights: ['Acceder gratuitamente a sus datos.', 'Conocer, actualizar y rectificar información.', 'Solicitar prueba de la autorización.', 'Presentar quejas ante la autoridad competente.', 'Revocar la autorización o solicitar supresión cuando proceda.', 'Abstenerse de responder preguntas sobre datos sensibles.'],
      channelTitle: 'Canal de atención',
      channelText: 'Las consultas y solicitudes relacionadas con datos personales se reciben en info@eaglecommercial.com.co o en la sede corporativa vigente.'
    }
  },
  en: {
    home: {
      eyebrow: 'Technology engineering and integration from Colombia',
      title: 'Advanced technology to protect, connect and anticipate.',
      lead: 'Eagle Commercial integrates engineering and advanced technology solutions for defense, security, critical infrastructure and organizations operating where reliability is non-negotiable.',
      primary: 'Explore our capabilities',
      secondary: 'Talk to a specialist',
      heroNotes: ['Technology selected around the mission', 'Local integration, deployment and support', 'Technical information under controlled access'],
      principle: 'Solutions designed around the mission, not around a catalogue.',
      principleItems: ['Engineering', 'Integration', 'Deployment', 'Support'],
      introEyebrow: 'Company',
      introTitle: 'We integrate technology for critical operations.',
      introText: 'Eagle Commercial is a Colombian company focused on identifying, integrating and implementing technology solutions for public and private organizations. We combine engineering, local knowledge, access to specialized suppliers and technical support to turn complex needs into dependable capabilities.',
      introText2: 'Our work spans initial assessment, architecture design, logistics, installation, training and lifecycle support.',
      experienceEyebrow: 'Institutional experience',
      experienceTitle: 'Experience with demanding institutions and organizations.',
      experienceLead: 'We can present experience in a more dynamic way through a continuous strip of institutions with which projects and commercial relationships have been developed.',
      solutionsEyebrow: 'Featured solutions',
      solutionsTitle: 'Capabilities that create visual impact from the first visit.',
      solutionsLead: 'A solution showcase was added with reference imagery and concise descriptions to demonstrate portfolio breadth without overcrowding the page.',
      partnersEyebrow: 'Technology ecosystem',
      partnersTitle: 'Reference manufacturers and brands in our ecosystem.',
      partnersLead: 'This section introduces partners, manufacturers or technology references with a corporate approach. It can later be expanded with official logos once explicit publishing authorization exists.',
      capabilityEyebrow: 'Capabilities',
      capabilityTitle: 'Technology articulated as a system.',
      capabilityLead: 'We present general capabilities rather than public product catalogues. Configuration, availability and scope are defined after understanding the requirement and validating the applicable framework.',
      sectorsEyebrow: 'Sectors',
      sectorsTitle: 'Technology beyond a single environment.',
      sectorsLead: 'Our capabilities can adapt to public and private organizations that need to protect assets, maintain communications, monitor operations or act in complex scenarios.',
      processEyebrow: 'Methodology',
      processTitle: 'From need to operational capability.',
      processLead: 'We do more than supply equipment. We design a coherent solution, support implementation and help preserve its value over time.',
      diffEyebrow: 'Differentiators',
      diffTitle: 'An integrated capability, supported locally.',
      confidentialityEyebrow: 'Confidentiality',
      confidentialityTitle: 'Strategic technology requires discretion.',
      confidentialityText: 'Part of our portfolio and projects is subject to confidentiality restrictions. Detailed technical information is shared only with authorized organizations and users after the scope of the requirement has been validated.',
      groupEyebrow: 'Eagle Group',
      groupTitle: 'A structure prepared for complete projects.',
      groupText: 'The Eagle ecosystem connects commercial, technical, logistics, storage and customs capabilities to support projects from planning through delivery and support.',
      finalTitle: 'Let’s discuss your next capability.',
      finalText: 'Tell us about the environment, challenge or outcome you need. Our team will guide the next step without requesting sensitive information through public channels.'
    },
    company: {
      eyebrow: 'Our company',
      title: 'Engineering, technology and trust for demanding environments.',
      lead: 'Eagle Commercial S.A. connects engineering, integration, implementation and support capabilities for public and private organizations in Colombia.',
      thesisTitle: 'We build capabilities, not isolated technology purchases.',
      thesisText: 'Each project begins with an operational need rather than a product. We assess the environment, constraints, available infrastructure and expected outcome before selecting and integrating technologies.',
      thesisText2: 'Our role is to connect specialized suppliers with the local context and support the project from definition through lifecycle service.',
      principlesTitle: 'Principles guiding our work',
      principles: [
        { title: 'Responsibility', text: 'Technology is proposed, integrated and delivered within the applicable legal, contractual and ethical framework.' },
        { title: 'Confidentiality', text: 'Technical, commercial and operational information is shared according to need, authorization and access level.' },
        { title: 'Rigor', text: 'Decisions are based on requirements, compatibility, testing, documentation and traceability.' },
        { title: 'Continuity', text: 'Training, maintenance, warranties and evolution are considered from the initial design.' }
      ],
      modelEyebrow: 'Operating model',
      modelTitle: 'A bridge between international technology and local requirements.',
      modelText: 'Eagle Commercial combines knowledge of the Colombian market, project management, supplier relationships, specialized logistics, implementation and technical support.',
      audienceTitle: 'We work with organizations that cannot improvise.',
      audienceText: 'Public entities, critical infrastructure, private companies, industrial operators and international partners find in Eagle a counterpart for structuring complex technology projects.',
      finalTitle: 'See how we approach a project.',
      finalText: 'Our methodology provides an orderly path from requirement to deployment and support.'
    },
    capabilities: {
      eyebrow: 'Capabilities',
      title: 'A portfolio view without exposing sensitive information.',
      lead: 'Public information describes general benefits and scenarios. Models, brands, specifications, configurations and technical scope are shared only through an authorized process.',
      noteTitle: 'Technical information with context and authorization',
      noteText: 'Availability, configuration and scope depend on technical analysis, regulations, project conditions and authorization to share information.',
      processTitle: 'How to enquire about a capability',
      process: ['Share the general objective without restricted information.', 'Our team validates the context and access level.', 'An appropriate channel and, where needed, a confidentiality agreement are established.', 'An architecture tailored to the requirement is presented.'],
      finalTitle: 'Is your need not listed here?',
      finalText: 'Capabilities can be combined in custom projects. Describe the expected outcome and general environment.'
    },
    sectors: {
      eyebrow: 'Sectors',
      title: 'Technology for public and private operations.',
      lead: 'Capability value depends on context. We adapt architecture, deployment, training and support to each sector’s reality.',
      crossTitle: 'One principle, different missions.',
      crossText: 'Protecting a facility, inspecting an asset, maintaining connectivity or coordinating an emergency requires understanding risks, users, infrastructure and regulation. That is why we avoid generic solutions.',
      finalTitle: 'Explore an architecture for your sector.',
      finalText: 'Talk with our team about the environment, assets and outcome you need.'
    },
    engineering: {
      eyebrow: 'Engineering and integration',
      title: 'We design around the operational outcome.',
      lead: 'Technology selection is one stage of the process. First we define the problem, interfaces, risks, acceptance criteria and sustainment plan.',
      architectureTitle: 'A complete architecture considers more than equipment.',
      architectureItems: [
        { title: 'People', text: 'Roles, profiles, training, workload and knowledge transfer.' },
        { title: 'Processes', text: 'Workflows, escalation, documentation, governance and decision criteria.' },
        { title: 'Technology', text: 'Compatibility, integration, communications, processing, energy and cybersecurity.' },
        { title: 'Environment', text: 'Infrastructure, climate, mobility, regulation, logistics and operating constraints.' }
      ],
      evidenceTitle: 'Deliverables that improve traceability',
      evidenceItems: ['Scope and assumptions', 'Functional architecture', 'Integration and test plan', 'Acceptance criteria', 'Training plan', 'Delivery documentation', 'Support and continuity plan'],
      finalTitle: 'Structure the project before discussing references.',
      finalText: 'A well-framed initial conversation reduces risk, avoids isolated purchases and accelerates a viable solution.'
    },
    support: {
      eyebrow: 'Support and lifecycle',
      title: 'Delivery is the beginning of operation.',
      lead: 'A technology capability preserves its value through assistance, knowledge, maintenance, documentation and a path for evolution.',
      modelTitle: 'Support aligned with criticality.',
      modelText: 'Scope is defined contractually according to location, required availability, response times, spares, warranties, supplier access and security restrictions.',
      continuityTitle: 'Continuity by design',
      continuityItems: ['Critical component identification', 'Support and escalation matrix', 'Maintenance plan', 'Obsolescence management', 'Document backup', 'Recurring training'],
      finalTitle: 'Do you need support for an existing capability?',
      finalText: 'Share only the general category and type of issue. Our team will indicate the secure channel for the next step.'
    },
    group: {
      eyebrow: 'Eagle Group',
      title: 'Engineering, logistics and foreign trade in coordination.',
      lead: 'Specialized projects require more than technology selection. They also need storage, preparation, traceability, customs clearance and document coordination.',
      flowTitle: 'A connected chain that reduces friction.',
      flowSteps: ['Technical and commercial structuring', 'Supplier coordination', 'Logistics and storage', 'Applicable customs processes', 'Delivery, implementation and support'],
      governanceTitle: 'Each service retains its own scope and responsibility.',
      governanceText: 'Legal names, authorizations and service conditions must be validated before publication. Contracting and execution follow the relevant entity and scope.',
      finalTitle: 'Start with the right point of contact.',
      finalText: 'Eagle Commercial will guide the request to the appropriate technical, logistics or customs component.'
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Let’s talk without exposing sensitive information.',
      lead: 'Describe the general objective, sector and expected outcome. Our team will establish an appropriate channel when confidentiality is required.',
      detailsTitle: 'Contact information',
      formTitle: 'Request guidance',
      formIntro: 'Fields marked are required. Do not attach documents or include specifications, sensitive locations or classified information.',
      types: ['Corporate information', 'Needs assessment', 'Technology project', 'Technical support', 'International partnership', 'Access request', 'Other'],
      urgency: ['Planning', 'This quarter', 'Within the next few weeks', 'Incident or operational continuity'],
      submit: 'Prepare message',
      privacyText: 'I authorize the processing of my data to respond to this request under the applicable policy.'
    },
    access: {
      eyebrow: 'Authorized access',
      title: 'Technical information for previously validated users.',
      lead: 'Restricted information should be hosted on a separate platform with authentication, role control, activity logs and confidentiality agreements.',
      loginTitle: 'Sign in',
      requestTitle: 'Request access',
      loginButton: 'Sign in',
      requestButton: 'Submit request',
      rulesTitle: 'Minimum requirements for the production system',
      rules: ['Multi-factor authentication', 'Manual user approval', 'Access by organization, role and project', 'Activity and download logs', 'Expiring links and permissions', 'Terms and NDA acceptance', 'Hosting and encryption approved by IT']
    },
    privacy: {
      eyebrow: 'Privacy and cookies',
      title: 'Transparency in the use of information.',
      lead: 'This copy is a functional prototype draft and requires legal review before publication.',
      sections: [
        { title: 'Scope', text: 'The policy should explain what information the site collects, why it is used, how long it is retained and with whom it may be shared.' },
        { title: 'Forms', text: 'Submitted data would be used to answer requests, assess opportunities, coordinate support and manage authorized business relationships.' },
        { title: 'Cookies', text: 'The prototype includes no analytics or advertising. It uses local storage only to remember the cookie notice preference.' },
        { title: 'Security', text: 'The production version should apply technical and administrative controls proportional to risk, including encryption, access control and traceability.' },
        { title: 'Rights', text: 'The final policy should describe channels to access, update, correct or delete information and withdraw consent where applicable.' },
        { title: 'Updates', text: 'Any change should identify its effective date, responsible party and notification mechanism.' }
      ]
    },
    data: {
      eyebrow: 'Personal data processing',
      title: 'Privacy notice and authorization.',
      lead: 'Content based on the existing public policy. It must be reviewed and updated by legal counsel before migration to the new site.',
      intro: 'Eagle Commercial S.A., tax identification number 830.040.391-7 and domiciled in Bogotá, acts as controller of personal information supplied through requests, business relationships, events, procurement processes and other authorized interactions.',
      purposesTitle: 'General purposes',
      purposes: ['Respond to requests and maintain internal databases.', 'Manage invitations, events, courses, seminars and training.', 'Assess satisfaction and conduct studies or diagnostics.', 'Carry out authorized commercial and relationship activities.', 'Manage suppliers and procurement processes.', 'Generate statistics and reports.', 'Respond to petitions and legal obligations.', 'Transmit information to partners or affiliates where a legal basis and applicable authorization exist.'],
      rightsTitle: 'Data subject rights',
      rights: ['Access personal data at no cost.', 'Know, update and correct information.', 'Request proof of authorization.', 'Submit complaints to the competent authority.', 'Withdraw authorization or request deletion where applicable.', 'Decline to answer questions about sensitive data.'],
      channelTitle: 'Contact channel',
      channelText: 'Queries and requests related to personal data are received at info@eaglecommercial.com.co or at the current corporate office.'
    }
  }
};
